name: TotalTeleportation
main: com.samoatesgames.totalteleportation.TotalTeleportation
version: 1.1
authors: [SamOatesPlugins]
description: A teleportation plugin.

commands:
    spawn:
        description: Teleport a player to spawn
        usage: /<command>
    setspawn:
        description: Set the spawn to a players current location
        usage: /<command>
    home:
        description: Teleport a player to their home
        usage: /<command>
    sethome:
        description: Set a players home to their current location
        usage: /<command>